import Head from "next/head";
import Image from "next/image";
import css from "../styles/Home.module.css";
import react, { useState } from "react";
import FirebaseAuthService from "../Firebase/FirebaseAuthService";


import NavBar from "../Components/NavBar";
import LoginForm from "../Components/LoginForm";
import Carousel from "../Components/Carousel";

export default function Home() {
    const [user, setUser] = useState(null);

    return (
        <div className={css.container}>
            <Head>
                <title>Fake Estate</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={css.global_container}>
                <NavBar existingUser={user} />
                <LoginForm />
                <Carousel/>

                <section className={css.test_section}>
                    <h1 className={css.title}>Ceci est un titre</h1>
                    <p className={css.para1}>
                        Lorem ipsum dolor sit, amet consectetur adipisicing
                        elit. Id accusantium molestias sint cupiditate nulla
                        laudantium.
                    </p>
                </section>
            </div>
        </div>
    );
}
