import Head from "next/head";
import Image from "next/image";
import css from "../styles/Home.module.scss";
import react, { useState, useContext, useEffect } from "react";
import firebase from "../Firebase/FirebaseConfig";

import FirebaseAuthService from "../Firebase/FirebaseAuthService";
import { db } from "../Firebase/FirebaseConfig";
import { Auth } from "firebase/auth";
import {
    collection,
    getDocs,
    addDoc,
    updateDoc,
    deleteDoc,
    doc,
    startAfter,
    deleteField,
} from "firebase/firestore";

import {
    handleFetchProducts,
    handleUpdateProduct,   
    handleAddProduct,
    handleEditProductClick,
    handleEditProductCancel,
} from "../Logic/Crud";

import { LoginContext } from "../context/LoginContext";

import NavBar from "../Components/NavBar";
import LoginForm from "../Components/LoginForm";
import Carousel from "../Components/Carousel";
import CreateEditForm from "../Components/CreateEditForm";

export default function Home() {
    const dataCollectionRef = collection(db, "test");
    const { user, setUser,  products, setProducts } = useContext(LoginContext);
    FirebaseAuthService.subscribeToAuthChanges(setUser);
    // const dataCollectionRef = collection(db, "test");

   
    const fetchData = async () => {
        const data = await getDocs(dataCollectionRef);
        setProducts(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));

       
    };
  
    useEffect(() => {
        fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

   
    return (
        <div className={css.container}>
            <Head>
                <title>Fake Estate</title>
                <meta
                    name="Fake EstateS"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={css.global_container}>
                <NavBar existingUser={user} />
                <LoginForm />

                {/* {user  ? "" : <Carousel />} */}

                <section className={css.test_section}>


                <Carousel/>


                    {/* {user ? (
                        <CreateEditForm handleAddProduct={handleAddProduct} />
                    ) : (
                        ""
                    )} */}
                </section>
            </div>
        </div>
    );
}
