import Head from "next/head";
import Image from "next/image";
import css from "../styles/Home.module.css";
import react, { useState, useContext } from "react";
import FirebaseAuthService from "../Firebase/FirebaseAuthService";
import FirebaseFirestoreService from '../Firebase/FirebaseFirestoreService'
import { LoginContext } from "../context/LoginContext";

import NavBar from "../Components/NavBar";
import LoginForm from "../Components/LoginForm";
import Carousel from "../Components/Carousel";
import CreateEditForm from "../Components/CreateEditForm";

export default function Home() {
    const { user, setUser } = useContext(LoginContext);

    FirebaseAuthService.subscribeToAuthChanges(setUser)

    const handleAddProduct = async (newProduct) => {
        try {
            const response = await FirebaseFirestoreService.createDocument('Products',  newProduct)
            alert(`successfully added new product with ID : ${response.id}  ! `)
        } catch (error) {
            alert(error.message)
        }
    }

    return (
        <div className={css.container}>
            <Head>
                <title>Fake Estate</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={css.global_container}>
                <NavBar existingUser={user} />
                <LoginForm />

                {/* {user  ? "" : <Carousel />} */}

                <section className={css.test_section}>
                    <h1 className={css.title}>Ceci est un titre</h1>
                {/* {user ? ( <CreateEditForm />) : ""} */}
                <CreateEditForm handleAddProduct={handleAddProduct} />
                </section>
            </div>
        </div>
    );
}
