import Head from "next/head";
import Image from "next/image";
import css from "../styles/Home.module.scss";
import react, { useState, useContext, useEffect } from "react";
import firebase from "../Firebase/FirebaseConfig";
import ParisCity from '../Assets/images_Carousel/ParisCity.jpg'
import Link from "next/link";
import FirebaseAuthService from "../Firebase/FirebaseAuthService";
import { db } from "../Firebase/FirebaseConfig";
import { Auth } from "firebase/auth";
import {
    collection,
    getDocs,
    addDoc,
    updateDoc,
    deleteDoc,
    doc,
    startAfter,
    deleteField,
} from "firebase/firestore";

import {
    handleFetchProducts,
    handleUpdateProduct,   
    handleAddProduct,
    handleEditProductClick,
    handleEditProductCancel,
} from "../Logic/Crud";

import { LoginContext } from "../context/LoginContext";

import NavBar from "../Components/NavBar";
import LoginForm from "../Components/LoginForm";
import Carousel from "../Components/Carousel";
import CreateEditForm from "../Components/CreateEditForm";
import Footer from "../Components/Footer";

export default function Home() {
    const dataCollectionRef = collection(db, "test");
    const { user, setUser,  products, setProducts } = useContext(LoginContext);
    FirebaseAuthService.subscribeToAuthChanges(setUser);
    // const dataCollectionRef = collection(db, "test");

   
    const fetchData = async () => {
        const data = await getDocs(dataCollectionRef);
        setProducts(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));

       
    };
  
    useEffect(() => {
        fetchData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [])

   
    return (
        <div className={css.container}>
            <Head>
                <title>Fake Estate</title>
                <meta
                    name="Fake Estate"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={css.global_container}>
                <NavBar existingUser={user} />
                <LoginForm />
              


                <section className={css.test_section}>
                <div>
                    <h1 className={css.title} >Fake Estate</h1>
                </div>

                <Carousel/>


                  
                </section>

                <section className={css.middle_part}>
                    <div className={css.title_logo_container}>
                        <h2>FAKE ESTATE</h2>
                        <h3> VOTRE AGENCE AU COEUR DE PARIS</h3>
                        <div>

                        <Link href="AboutPage">
                            <button className={css.info_button}> Plus d'infos</button>
                        </Link>
                        </div>
                    </div>

                    <div className={css.image_container} >
                        <Image
                            src={ParisCity}
                            alt="image de paris"
                            width={100}
                            height={100}
                            layout="responsive"
                        />
                    </div>

                    <div className={css.text_container}>
                        <p>Installés à proximité de la comédie Française, cela fait maintenant dix ans que nous sommes spécialisés dans la vente et location de biens immobiliers français pour une clientèle japonaise</p>
                        <p>En vente nous proposons notamment des appartements, mais aussi des locaux commerciaux tels que boutiques ou restaurants, notre périmètre s’étend de l’Opéra Garnier jusqu’aux alentours du Musée du Louvre.</p>
                    </div>
                </section>
            </div>
            <Footer/>
        </div>
    );
}
